name: Deploy to GitHub Packages

on:
  push:
    tags:
      - 'v*'  # This will trigger on tags like 'v1.0.0'
  workflow_dispatch:   # This allows the workflow to be manually triggered via API

jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file


      - name: Build with Maven
        run: mvn clean install

      - name: Publish to GitHub Packages
        run: mvn deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/charlottekies/algo-utils
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
